### ISSUE TITLE
Adding hpack?

### ISSUE THREAD

**Issue by chiroptical** [utdemir/hs-nix-template#20]
Hey, I recently discovered this template and it is super helpful. I was wondering if you think adding hpack would be beneficial to the template? The nix build automatically picks it up and you don't have to add all of your modules to the cabal file.

I would gladly do the work, but I wanted to see if it aligns with your view of the project :)

**Comment by utdemir** [comment]
>  The nix build automatically picks it up and you don't have to add all of your modules to the cabal file.

I didn't know `cabal2nix` had hpack support, cool!

> but I wanted to see if it aligns with your view of the project :)

Even though I am not a hpack user, I am happy with having it as an optional feature. What I would only ask is that if we could also extend the current tests somehow to test the new functionality.

>  I would gladly do the work, 

Thanks! Let me know if there's anything I can help with.
