### ISSUE TITLE
github actions workflow with multiple lines?

### ISSUE THREAD

**Issue by chiroptical** [utdemir/hs-nix-template#25]
https://github.com/utdemir/hs-nix-template/blob/92478119289f828645d56721df7f1450bdd44861/.github/workflows/build.yaml#L19

While working on #22, we tried using the multiline syntax (from https://yaml-multiline.info). Basically, writing,

```yaml
 - run: >-
   nix-build ci.nix
     --argstr use_hpack "${{ matrix.use_hpack }}"
     --argstr add_executable_section "${{ matrix.add_executable_section }}" 
```

However, this caused CI to fail. I tried both `>`, `>-` and,

```yaml
 - run: |
   nix-build ci.nix \
     --argstr use_hpack "${{ matrix.use_hpack }}" \
     --argstr add_executable_section "${{ matrix.add_executable_section }}" 
```

None of these work. If anyone knows how these things work that would be great :)

**Comment by utdemir** [comment]
#26 fixes this! It looks similar to the snippet on your description, so I don't really know what exactly fixed this. Maybe the indentation.
