### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by codygman** [utdemir/hs-nix-template#9]
I'd like to fork this if only to have a public CI to see errors but there isn't a license, can you please add one?

**Comment by utdemir** [comment]
Sure, I'll add a permissive one. Also, I'm slowly moving away from Buildkite to GitHub actions, so the public CI issue will be solved these days.

**Comment by utdemir** [comment]
Hey @codygman, just wanted to let you know that I made some fixes to the CI and made it public, if you're interested.

**Comment by codygman** [comment]
Thanks! The CI being public likely scratches my itch.

The template is great btw. With Lorrie/direnv, any project I open with a .envrc and shell.nix just works.

I can't wait until hie/hie get sorted out and will help if I can.
